name: Build Python module using pip

# The CI pipeline build script is currently disabled due to issues with the CUDA installation.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}
    name: "Build Python module on ${{ matrix.os }} using pip"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13' 

      - name: Build
        shell: bash -el {0}
        run: |
          pip install numpy
          echo "python:"
          which python
          echo "python3:"
          which python3
          echo "pip:"
          which pip
          echo "pip3:"
          which pip3
          pip install .
