name: Test vcpkg python3 pip

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-20.04
    name: "Test vcpkg python3 pip"

    env:
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg-master

    steps:
    - name: Test pip installation
      shell: bash
      run: |
        git clone https://github.com/microsoft/vcpkg.git $VCPKG_ROOT
        $VCPKG_ROOT/vcpkg install python3
        $VCPKG_ROOT/packages/python3_x64-linux/tools/python3/python3.10 -m ensurepip --upgrade
