name: Test vcpkg python3 pip

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, ubuntu-22.04, windows-2019 ]

    runs-on: ${{ matrix.os }}
    name: "Test vcpkg python3 pip"

    env:
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg-master

    steps:
    - name: Test pip installation
      shell: bash
      run: |
        echo "Test"
        git clone https://github.com/microsoft/vcpkg.git $VCPKG_ROOT
        "$VCPKG_ROOT/bootstrap-vcpkg.sh" -disableMetrics
        "$VCPKG_ROOT/vcpkg" install python3
        "$VCPKG_ROOT/packages/python3_x64-linux/tools/python3/python3.10" -m ensurepip --upgrade
