name: Build using vcpkg

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, windows-2022, macos-latest ]

    runs-on: ${{ matrix.os }}
    name: "${{ github.workflow }}: ${{ matrix.os }}"

    env:
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg
      VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg/bincache

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: actions/checkout@v2
      with:
        repository: chrismile/sgl
        path: sgl-repo
        submodules: true

    - uses: lukka/get-cmake@latest

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v10.1
      with:
        vcpkgUrl: 'https://github.com/zmughal/vcpkg.git'
        vcpkgCommitId: 'af06f79f8d4e6dc5aca80c77565a729f54797f44'
        #doNotCacheOnWorkflowFailure: true

    - name: Configure CMake
      shell: bash
      run: |
        cmake -B "${{github.workspace}}/build" -DCMAKE_TOOLCHAIN_FILE="${{env.VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build "${{github.workspace}}/build" --config ${{env.BUILD_TYPE}} --parallel 4

    - name: Remove symbolic links before caching (Windows only)
      if: runner.os == 'Windows'
      shell: bash
      run: |
        find "${{env.VCPKG_ROOT}}/buildtrees" -type l -exec echo {} \;
        find "${{env.VCPKG_ROOT}}/buildtrees" -type l -exec rm {} \;
