name: Test vcpkg python3 pip (dynamic)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04 ]

    runs-on: ${{ matrix.os }}
    name: "Test vcpkg python3 pip (dynamic)"

    env:
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg-master

    steps:
    - name: Test pip installation
      shell: bash
      run: |
        git clone https://github.com/microsoft/vcpkg.git $VCPKG_ROOT
        "$VCPKG_ROOT/bootstrap-vcpkg.sh" -disableMetrics
        cp "$VCPKG_ROOT/triplets/x64-linux.cmake" "$VCPKG_ROOT/triplets/x64-linux-dynamic.cmake"
        sed -i -e 's/VCPKG_LIBRARY_LINKAGE static/VCPKG_LIBRARY_LINKAGE dynamic/g' "$VCPKG_ROOT/triplets/x64-linux-dynamic.cmake"
        "$VCPKG_ROOT/vcpkg" install --triplet=x64-linux-dynamic python3
        export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$VCPKG_ROOT/installed/x64-linux-dynamic/lib"
        PYTHON_EXECUTABLE="$VCPKG_ROOT/installed/x64-linux-dynamic/tools/python3/python3.10"
        "$PYTHON_EXECUTABLE" -m ensurepip --upgrade
        "$PYTHON_EXECUTABLE" -m pip install numpy
