name: Build Python module using pip

# The CI pipeline build script is currently disabled due to issues with the CUDA installation.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}
    name: "Build Python module on ${{ matrix.os }} using pip"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      # On 2025-03-10, this action resulted in "System.IO.IOException: No space left on device".
      - name: Clean up unused files
        if: runner.os == 'Linux'
        run: |
          # Code below from: https://carlosbecker.com/posts/github-actions-disk-space/
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo docker builder prune -a

      - name: Build
        shell: bash -el {0}
        run: |
          # export CONDA_ALWAYS_YES="true"
          # conda install numpy sympy numba matplotlib tqdm scikit-image conda-forge::tensorboard conda-forge::opencv \
          # conda-forge::openexr-python pytorch torchvision torchaudio cpuonly -c pytorch
          pip install numpy sympy numba matplotlib tqdm scikit-image tensorboard opencv-python openexr
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          echo "python:"
          which python
          echo "python3:"
          which python3
          echo "pip:"
          which pip
          echo "pip3:"
          which pip3
          pip install .
