name: Test vcpkg python3 pip

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-20.04
    name: "Test vcpkg python3 pip"

    env:
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg
      VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg/bincache

    steps:
    - name: Install Vulkan SDK
      shell: bash
      run: |
        vcpkg install python3
        $VCPKG_ROOT/packages/python3_x64-linux/tools/python3/python3.10 -m ensurepip --upgrade
