name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-20.04
    name: "${{ github.workflow }}"

    steps:
    - name: Tests
      id: tests
      shell: bash
      run: |
        echo "USER=$USER" >> $GITHUB_ENV
        echo "$USER"
        ls /home
        mkdir -p /home/$USER/.config/linevis
        echo "Test content in logfile" >> /home/$USER/.config/linevis/Logfile.html
        exit 1
        
    - name: Archive logs and failure case images
      if: always() && steps.tests.outcome == 'failure'
      uses: actions/upload-artifact@v2
      with:
        name: vpt-output-images
        path: |
          /home/${{env.USER}}/.config/linevis/Logfile.html
          ${{github.workspace}}/build/*.png
